language: node_js

branches:
  only:
    - master
    - stg

env:
  global:
    - TEST_RESULTS_DIR=./shippable/testresults
    - CODE_COVERAGE_DIR=./shippable/codecoverage
    - TESTS_LOC_DIR=./tests
    - MOD_LOC=./node_modules/.bin/

build:
  ci:
    - shipctl retry "npm install"
    - mkdir -p $TEST_RESULTS_DIR && mkdir -p $CODE_COVERAGE_DIR
    - $MOD_LOC/mocha --recursive "$TESTS_LOC_DIR/**/*.spec.js" -R mocha-junit-reporter --reporter-options mochaFile=$TEST_RESULTS_DIR/testresults.xml
    - $MOD_LOC/istanbul --include-all-sources cover -root "$SHIPPABLE_REPO_DIR/routes" ./node_modules/mocha/bin/_mocha -- -R spec-xunit-file --recursive "$TESTS_LOC_DIR/**/*.spec.js"
    - $MOD_LOC/istanbul report cobertura --dir $CODE_COVERAGE_DIR

  post_ci:
    - DH_USR_NAME=$(shipctl get_integration_resource_field git_pr_img_preq "userName")
    - DH_PASS=$(shipctl get_integration_resource_field git_pr_img_preq "password")
    - docker login -u $DH_USR_NAME -p $DH_PASS
    - APP_IMG=$(shipctl get_resource_version_key git_pr_img_preq "sourceName")
    - export
    - |
        if [ "$IS_PULL_REQUEST" == true ]; then
          export APP_TAG="pr."$PULL_REQUEST;
        else
          export APP_TAG=$BRANCH.$BUILD_NUMBER;
        fi
    - docker build -t $APP_IMG:$APP_TAG .
  on_success:
    - docker push $APP_IMG:$APP_TAG
    - |
        if [ "$IS_PULL_REQUEST" == true ]; then
          shipctl put_resource_state_multi git_pr_img_preq "versionName=$APP_TAG buildNumber=$BUILD_NUMBER commitSha=$COMMIT prNumber=$PULL_REQUEST";
        else
          shipctl put_resource_state_multi "git_pr_img_"$BRANCH "versionName=$APP_TAG buildNumber=$BUILD_NUMBER commitSha=$COMMIT branch=$BRANCH";
        fi


resources:
  - name: git_pr_cfg_repo
    type: gitRepo
    integration: "drship_github"
    versionTemplate:
      sourceName: "devops-recipes/git_pr_flow"
      branch: master

  - name: git_pr_img_preq
    type: image
    integration: drship_dockerhub
    versionTemplate:
      sourceName: "devopsrecipes/git_pr_flow_app"
      versionName: latest

  - name: git_pr_img_master
    type: image
    integration: drship_dockerhub
    versionTemplate:
      sourceName: "devopsrecipes/git_pr_flow_app"
      versionName: latest

  - name: git_pr_img_stg
    type: image
    integration: drship_dockerhub
    versionTemplate:
      sourceName: "devopsrecipes/git_pr_flow_app"
      versionName: latest

  - name: git_pr_gcp
    type: cliConfig
    integration: "drship_gcp"

jobs:
  - name: git_pr_flow_runCI
    type: runCI
    dependencyMode: strict
    triggerMode: parallel
    steps:
      - OUT: git_pr_img_stg
      - OUT: git_pr_img_master
      - OUT: git_pr_img_preq
    flags:
      - git_pr
      - ci

  - name: deploy_git_pr_preq
    type: runSh
    steps:
      - IN: git_pr_img_preq
      - IN: git_pr_gcp
        switch: off
      - IN: git_pr_cfg_repo
        switch: off
      - TASK:
          name: deploy_pReqs
          runtime:
            options:
              env:
                - APP_LABEL: "git-pr-app"
                - APP_NAMESPACE: "pull_req"
                - CLUSTER: "cluster"
                - REGION: "us-west1-a"
          script:
            - pushd $(shipctl get_resource_state "git_pr_cfg_repo")/specs
            - export APP_IMG=$(shipctl get_resource_version_key git_pr_img_preq sourceName)
            - export APP_TAG=$(shipctl get_resource_version_key git_pr_img_preq versionName)
            - shipctl replace appDeploy.yml appSvc.yml
            - gcloud container clusters get-credentials $CLUSTER --zone $REGION
            - kubectl delete  -f ./appDeploy.yml 2>/dev/null || echo ""
            - kubectl delete -f ./appSvc.yml  2>/dev/null || echo ""
            - kubectl create -o json -f ./appDeploy.yml >> kube_output.json
            - kubectl create -o json -f ./appSvc.yml >> kube_output.json
    always:
      script:
        - kubectl delete  -f ./appDeploy.yml 2>/dev/null || echo ""
        - kubectl delete -f ./appSvc.yml  2>/dev/null || echo ""
    flags:
      - gke
      - cd
      - kctl
      - git_pr

  - name: deploy_git_pr_stg
    type: runSh
    steps:
      - IN: git_pr_img_stg
      - IN: git_pr_gcp
        switch: off
      - IN: git_pr_cfg_repo
        switch: off
      - TASK:
          name: deploy_pReqs
          runtime:
            options:
              env:
                - APP_LABEL: "git-pr-app"
                - APP_NAMESPACE: "stg"
                - CLUSTER: "cluster"
                - REGION: "us-west1-a"
          script:
            - pushd $(shipctl get_resource_state "git_pr_cfg_repo")/specs
            - export APP_IMG=$(shipctl get_resource_version_key git_pr_img_stg sourceName)
            - export APP_TAG=$(shipctl get_resource_version_key git_pr_img_stg versionName)
            - shipctl replace appDeploy.yml appSvc.yml
            - gcloud container clusters get-credentials $CLUSTER --zone $REGION
            - kubectl delete  -f ./appDeploy.yml 2>/dev/null || echo ""
            - kubectl delete -f ./appSvc.yml  2>/dev/null || echo ""
            - kubectl create -o json -f ./appDeploy.yml >> kube_output.json
            - kubectl create -o json -f ./appSvc.yml >> kube_output.json
            - popd
    flags:
      - gke
      - cd
      - kctl
      - git_pr

  - name: deploy_git_pr_master
    type: runSh
    steps:
      - IN: git_pr_img_master
      - IN: git_pr_gcp
        switch: off
      - IN: git_pr_cfg_repo
        switch: off
      - TASK:
          name: deploy_pReqs
          runtime:
            options:
              env:
                - APP_LABEL: "git-pr-app"
                - APP_NAMESPACE: "master"
                - CLUSTER: "cluster"
                - REGION: "us-west1-a"
          script:
            - pushd $(shipctl get_resource_state "git_pr_cfg_repo")/specs
            - export APP_IMG=$(shipctl get_resource_version_key git_pr_img_master sourceName)
            - export APP_TAG=$(shipctl get_resource_version_key git_pr_img_master versionName)
            - shipctl replace appDeploy.yml appSvc.yml
            - gcloud container clusters get-credentials $CLUSTER --zone $REGION
            - kubectl delete  -f ./appDeploy.yml 2>/dev/null || echo ""
            - kubectl delete -f ./appSvc.yml  2>/dev/null || echo ""
            - kubectl create -o json -f ./appDeploy.yml >> kube_output.json
            - kubectl create -o json -f ./appSvc.yml >> kube_output.json
            - popd
    flags:
      - gke
      - cd
      - kctl
      - git_pr